name: money_tracker
description: Money Tracker

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  provider: ^6.0.2
  month_picker_dialog: ^0.4.0
  flutter_colorpicker: ^1.0.3
  syncfusion_flutter_charts: ^20.1.48
  flutter_slidable: ^1.2.0
  image_picker: ^0.8.5
  flutter_i18n: ^0.32.2
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.4
  freezed: ^1.0.0
  json_serializable: ^6.1.4
  mobx_codegen: ^2.0.3
  flutter_launcher_icons: ^0.9.2
  cached_network_image: ^3.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n_namespace/en/
    - assets/i18n_namespace/ru/
